[package]
name = "runevm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
bitflags = "1.3.2"
byteorder = "1.4.3"
clap = { version = "4.1.6", features = ["derive"] }
thiserror = "1.0.38"
