[package]
name = "runevm"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[dependencies]
bitflags = "1.3.2"
byteorder = "1.4.3"
clap = { version = "4.1.6", features = ["derive"] }